framework:
    messenger:
        failure_transport: failed
        default_bus:  messenger.bus.command

        buses:
            messenger.bus.command:
                middleware:
                    - doctrine_close_connection
                    - doctrine_transaction

            messenger.bus.query:
                default_middleware: false
                middleware:
                    - handle_message

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'

