# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    PocketShares\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Kernel.php'

    GuzzleHttp\Client:
        class: GuzzleHttp\Client

    PocketShares\Shared\Infrastructure\Bus\MessengerCommandBus:
        arguments:
            - '@messenger.bus.command'

    PocketShares\Shared\Infrastructure\Bus\MessengerQueryBus:
        arguments:
            - '@messenger.bus.query'

    PocketShares\Portfolio\Infrastructure\Repository\RegisterTransaction\TransactionRegistryProcessor:
        autowire: false
        arguments:
            - !tagged_iterator portfolio.transaction.strategy

    PocketShares\ExchangeRates\Provider\Nbp\Api\ApiClient:
        arguments:
            $client: '@GuzzleHttp\Client'

    _instanceof:
        PocketShares\Shared\Application\Command\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.command }

        PocketShares\Shared\Application\Query\QueryHandlerInterface:
            public: true
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.query }

        PocketShares\Portfolio\Infrastructure\Repository\RegisterTransaction\Strategy\RegisterTransactionStrategyInterface:
            tags: [ 'portfolio.transaction.strategy' ]